DROP TABLE tblEmployee CASCADE CONSTRAINTS;
DROP TABLE tblDepartment CASCADE CONSTRAINTS;
DROP TABLE tblDeptLocations CASCADE CONSTRAINTS;
DROP TABLE tblProject CASCADE CONSTRAINTS;
DROP TABLE tblWorksOn CASCADE CONSTRAINTS;
DROP TABLE tblDependent CASCADE CONSTRAINTS;
DROP TABLE audit_trail CASCADE CONSTRAINTS;
